import { AccessibilitySettings, AccessibilityPreset } from '@/types/accessibility.types';

export const DEFAULT_ACCESSIBILITY_SETTINGS: AccessibilitySettings = {
  highContrast: false,
  largeText: false,
  reducedMotion: false,
  keyboardNavigation: true,
  largeClickTargets: false,
  extendedTimeout: false,
  visualAlerts: true,
  simplifiedInterface: false,
  dyslexiaFriendly: false,
  readingGuide: false,
  reducedDistractions: false,
};

export const ACCESSIBILITY_PRESETS: Record<AccessibilityPreset, AccessibilitySettings> = {
  default: DEFAULT_ACCESSIBILITY_SETTINGS,
  blind: {
    highContrast: true,
    largeText: true,
    reducedMotion: true,
    keyboardNavigation: true,
    largeClickTargets: true,
    extendedTimeout: true,
    visualAlerts: true,
    simplifiedInterface: true,
    dyslexiaFriendly: false,
    readingGuide: true,
    reducedDistractions: true,
  },
  lowVision: {
    highContrast: true,
    largeText: true,
    reducedMotion: false,
    keyboardNavigation: true,
    largeClickTargets: true,
    extendedTimeout: false,
    visualAlerts: true,
    simplifiedInterface: false,
    dyslexiaFriendly: true,
    readingGuide: true,
    reducedDistractions: false,
  },
  motor: {
    highContrast: false,
    largeText: true,
    reducedMotion: true,
    keyboardNavigation: true,
    largeClickTargets: true,
    extendedTimeout: true,
    visualAlerts: true,
    simplifiedInterface: false,
    dyslexiaFriendly: false,
    readingGuide: false,
    reducedDistractions: false,
  },
  hearing: {
    highContrast: false,
    largeText: false,
    reducedMotion: false,
    keyboardNavigation: true,
    largeClickTargets: false,
    extendedTimeout: false,
    visualAlerts: true,
    simplifiedInterface: false,
    dyslexiaFriendly: false,
    readingGuide: false,
    reducedDistractions: false,
  },
  cognitive: {
    highContrast: false,
    largeText: true,
    reducedMotion: true,
    keyboardNavigation: true,
    largeClickTargets: false,
    extendedTimeout: true,
    visualAlerts: true,
    simplifiedInterface: true,
    dyslexiaFriendly: true,
    readingGuide: true,
    reducedDistractions: true,
  },
};

export const ACCESSIBILITY_STORAGE_KEY = 'foodie-accessibility';

export const ACCESSIBILITY_LABELS = {
  highContrast: 'Alto Contraste',
  largeText: 'Texto Grande',
  reducedMotion: 'Reduzir Animações',
  keyboardNavigation: 'Navegação por Teclado',
  largeClickTargets: 'Áreas de Clique Maiores',
  extendedTimeout: 'Tempo Estendido',
  visualAlerts: 'Alertas Visuais',
  simplifiedInterface: 'Interface Simplificada',
  dyslexiaFriendly: 'Fonte Dislexia',
  readingGuide: 'Linha de Leitura',
  reducedDistractions: 'Reduzir Distrações',
} as const;

export const ACCESSIBILITY_DESCRIPTIONS = {
  highContrast: 'Aumenta o contraste entre cores para melhor visibilidade',
  largeText: 'Aumenta o tamanho do texto em toda a aplicação',
  reducedMotion: 'Desativa animações e transições',
  keyboardNavigation: 'Melhora a navegação usando apenas o teclado',
  largeClickTargets: 'Aumenta botões e áreas clicáveis',
  extendedTimeout: 'Aumenta o tempo para ações automáticas',
  visualAlerts: 'Mostra alertas visuais para notificações sonoras',
  simplifiedInterface: 'Remove elementos decorativos e simplifica o layout',
  dyslexiaFriendly: 'Usa fonte mais legível para pessoas com dislexia',
  readingGuide: 'Adiciona linha guia para ajudar na leitura',
  reducedDistractions: 'Oculta elementos secundários',
} as const;
